### ISSUE TITLE
Volo Lutu Launcher handle

### ISSUE THREAD

**Issue by filipahped** [matthewdean/bio-media-builds#2]
![billede_2024-12-03_034641061](https://github.com/user-attachments/assets/6a9df6cf-b2d8-494a-a4eb-6a9fe0a3f508)

The Volo-Lutu Launcher in QftT seems to have a handle protruding from the middle of the build, likely a 2l or 3l axle stuck in the liftarm attached to the trigger. Furthermore, in the model in LoMN, the trigger-liftarm seems to be attached at the tip of the trigger, so the Stud.io model should maybe reflect that.

**Comment by matthewdean** [comment]
Thanks for this detailed report! Yes, it does seem like there should be an axle there. I see the same thing depicted in the tool icon. I've updated the model.
![image](https://github.com/user-attachments/assets/d504c3b5-f788-45b3-966f-7c370ac04fad)

This also makes sense in light of the recently surfaced Tohunga prototype having an axle hole in its non-disc arm.
![image](https://github.com/user-attachments/assets/b1a4ebf2-b840-465c-b5a9-0e345ec1ebc4)

As far as the trigger liftarm's placement - I agree with you that in QftT, it appears to be placed at the end of the trigger's axle. Note that in the LoMN model, it appears to be placed close to the barrel. I will disregard LoMN's depiction because 1) I think this tool was designed for Tohunga and if it were placed so close, a Tohunga would not be able to securely carry it 2) its placement is impossibly close to the barrel because it does not account for the 0.5 stud block connecting the axle to the barrel.
